# Generated by Django 3.1.7 on 2021-04-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conectiondb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conectiondb.cafeteria')),
            ],
        ),
    ]
